/**
 * `pnpm dune:assemble` — compose the wallet-persistence queries, and optionally
 * push them to Dune.
 *
 * `ops/dune/wallet-persistence.sql` is one file with sections marked `--#BASE`,
 * `--#RANK`, `--#Q1` .. `--#Q10`, each closed by `--#END`, and each query declaring
 * what it needs with `needs=BASE,RANK`. This composes them into self-contained
 * statements under `ops/dune/generated/`.
 *
 * WHY THIS EXISTS
 *
 * The delivered v1 said "prepend the SHARED BASE block" and asked for a different
 * subset of it in two different places. v2 wrote the base out four times to avoid
 * that, which traded a hand-assembly step for four copies that can drift. Neither
 * is good: a query that is assembled by hand is a query where the thing that ran
 * and the thing in version control are different artifacts, and on a corpus this
 * expensive to scan that difference is not recoverable after the fact.
 *
 * So the file has ONE base, and the composition is code.
 *
 * --push additionally creates or updates the queries in Dune, reading the key
 * from `DUNE_API_KEY`. It never writes the key anywhere: not to the generated
 * files, not to the id map, not to stdout. Creating and updating a query costs no
 * credits; only executing does, which this script deliberately does not do.
 */
import { writeFileSync, mkdirSync, readFileSync, existsSync } from 'node:fs';

const NEWLINE = String.fromCharCode(10);
const SOURCE = 'ops/dune/wallet-persistence.sql';
const OUT_DIR = 'ops/dune/generated';
/** query name -> Dune query id, so a second push updates rather than duplicates. */
const ID_MAP = 'ops/dune/query-ids.json';

interface Section {
  readonly name: string;
  readonly needs: readonly string[];
  readonly body: string;
}

function sections(sql: string): Map<string, Section> {
  const out = new Map<string, Section>();
  let current: { name: string; needs: string[]; lines: string[] } | null = null;
  for (const line of sql.split('\n')) {
    const open = /^--#(?!END)([A-Z0-9-]+)(?:\s+needs=([A-Z0-9,-]+))?\s*$/.exec(line.trim());
    if (open !== null) {
      if (current !== null) throw new Error(`section ${open[1]} opened inside ${current.name}`);
      current = {
        name: open[1] as string,
        needs: (open[2] ?? '').split(',').filter((s) => s.length > 0),
        lines: [],
      };
      continue;
    }
    if (line.trim() === '--#END') {
      if (current === null) throw new Error('--#END with no open section');
      out.set(current.name, { name: current.name, needs: current.needs, body: current.lines.join('\n') });
      current = null;
      continue;
    }
    if (current !== null) current.lines.push(line);
  }
  if (current !== null) throw new Error(`section ${current.name} was never closed`);
  return out;
}

const sql = readFileSync(SOURCE, 'utf8');
const parsed = sections(sql);
for (const required of ['BASE', 'RANK', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q10', 'Q11']) {
  if (!parsed.has(required)) {
    console.error(`${SOURCE} is missing section ${required}`);
    process.exit(1);
  }
}

const compose = (q: Section): string => {
  const parts = q.needs.map((n) => {
    const dep = parsed.get(n);
    if (dep === undefined) throw new Error(`${q.name} needs ${n}, which is not a section`);
    return dep.body;
  });
  return [
    `-- GENERATED by pnpm dune:assemble from ${SOURCE} — do not edit here.`,
    `-- ${q.name}, composed from ${q.needs.join(' + ')} + ${q.name}.`,
    '',
    ...parts,
    q.body,
  ].join('\n');
};

/**
 * Remove the trailing statement terminator.
 *
 * DuneSQL wraps the submitted text and rejects a trailing `;` outright:
 *
 *   line 220:14: mismatched input ';'. Expecting: … <EOF>
 *
 * The source file keeps its semicolons, because it is also read by humans and
 * pasted into the Dune editor where the terminator is conventional. Stripping it
 * belongs here, at the boundary where the text becomes an API payload — the same
 * reason the statement count is asserted here rather than trusted.
 */
function stripTerminator(text: string): string {
  const lines = text.split(NEWLINE);
  for (let i = lines.length - 1; i >= 0; i -= 1) {
    const code = (lines[i] as string).replace(/--.*$/, '').trimEnd();
    if (code.length === 0) continue;
    if (!code.endsWith(';')) break;
    const at = (lines[i] as string).lastIndexOf(';');
    lines[i] = (lines[i] as string).slice(0, at) + (lines[i] as string).slice(at + 1);
    break;
  }
  return lines.join(NEWLINE);
}

mkdirSync(OUT_DIR, { recursive: true });
const composed = new Map<string, string>();
for (const name of ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q10', 'Q11']) {
  const text = stripTerminator(compose(parsed.get(name) as Section));
  composed.set(name, text);
  const path = `${OUT_DIR}/${name.toLowerCase()}.sql`;
  writeFileSync(path, text.endsWith('\n') ? text : `${text}\n`);
  // Count EXECUTABLE statements: strip line comments first, because the
  // generated header is a comment and a naive split counts it as a fragment.
  // Strip BLOCK comments before line comments. A `;` inside a /* … */ block is
  // not a statement terminator, and counting it as one refused a valid query —
  // the per-day panel note in Q3 contains a semicolon in prose.
  const bare = text
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .split(NEWLINE)
    .map((l) => l.replace(/--.*$/, ''))
    .join(NEWLINE);
  const statements = bare.split(';').filter((s) => s.trim().length > 0).length;
  console.log(`${path}  ${text.split('\n').length} lines, ${statements} statement(s)`);
  if (statements !== 1) {
    console.error(`  REFUSING: ${name} composed to ${statements} statements; Dune executes one per query`);
    process.exit(1);
  }
}

// ---------------------------------------------------------------------------
// --push
// ---------------------------------------------------------------------------

if (!process.argv.includes('--push')) {
  console.log('\nnot pushed. Re-run with --push and DUNE_API_KEY set to create or update the Dune queries.');
  process.exit(0);
}

const key = process.env['DUNE_API_KEY'] ?? '';
if (key.length === 0) {
  console.error('DUNE_API_KEY is not set. It is read from the environment and never written to a file.');
  process.exit(1);
}

const NAMES: Record<string, string> = {
  Q1: 'epitaxy · wallet persistence · Q1 reconstruction sanity',
  Q2: 'epitaxy · wallet persistence · Q2 fit ranking and disappearance',
  Q3: 'epitaxy · wallet persistence · Q3 holdout panel export',
  Q4: 'epitaxy · wallet persistence · Q4 token forward return by cohort',
  Q5: 'epitaxy · phase C · Q5 copier return by lag',
  Q6: 'epitaxy · phase C · Q6 rotation or death',
  Q7: 'epitaxy · phase D · Q7 paired round-trip copy',
  Q8: 'epitaxy · phase E · Q8 proportional exit mirroring',
  Q10: 'epitaxy · phase F · Q10 H1 at entity level',
  Q11: 'epitaxy · phase G · Q11 coverage by horizon (no returns)',
};

const ids: Record<string, number> = existsSync(ID_MAP)
  ? (JSON.parse(readFileSync(ID_MAP, 'utf8')) as Record<string, number>)
  : {};

const call = async (path: string, method: string, body: unknown): Promise<{ status: number; json: unknown }> => {
  const res = await fetch(`https://api.dune.com/api/v1${path}`, {
    method,
    headers: { 'X-Dune-API-Key': key, 'Content-Type': 'application/json' },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  let json: unknown = null;
  try {
    json = await res.json();
  } catch {
    json = null;
  }
  return { status: res.status, json };
};

for (const name of ['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q10', 'Q11']) {
  const text = composed.get(name) as string;
  const existing = ids[name];
  if (existing !== undefined) {
    const r = await call(`/query/${existing}`, 'PATCH', { query_sql: text, name: NAMES[name] });
    console.log(`${name}  PATCH ${existing}  status ${r.status}`);
    if (r.status !== 200) console.log(`   ${JSON.stringify(r.json).slice(0, 200)}`);
    continue;
  }
  const r = await call('/query', 'POST', { name: NAMES[name], query_sql: text, is_private: true });
  const id = (r.json as { query_id?: number } | null)?.query_id;
  console.log(`${name}  CREATE  status ${r.status}  id ${id ?? 'none'}`);
  if (id === undefined) {
    console.log(`   ${JSON.stringify(r.json).slice(0, 300)}`);
    continue;
  }
  ids[name] = id;
}

writeFileSync(ID_MAP, `${JSON.stringify(ids, null, 2)}\n`);
console.log(`\nwrote ${ID_MAP}. Nothing was executed: creating and updating a query costs no credits.`);
console.log('To run one:  curl -X POST -H "X-Dune-API-Key: $DUNE_API_KEY" \\');
console.log('               -d \'{"performance":"medium"}\' https://api.dune.com/api/v1/query/<id>/execute');
