/**
 * Phase G addendum §A.4 — generate the curve re-pricing query.
 *
 * The pump program emits its own curve state at every trade, so an exit price for a
 * censored position is not a reconstruction: it is the state the program reported at
 * the last trade at or before the target instant. A bonding curve's reserves change
 * ONLY when someone trades, so between trades the state is exactly constant and the
 * price is exact rather than interpolated.
 *
 * §A.3 validated the one assumption that carries: rolling `virtualTokenReserves`
 * forward on token amounts alone reproduces what the program reported at p50 1.00000
 * with 97.9%–99.5% inside 1% across every trade-count bucket. That is the test of
 * "reserves do not move without a trade", and it passes. The invariant-derived SOL
 * side FAILED (58.5%–80.0% within 1%), so `k` is not constant over a curve's life and
 * this query never uses it — the SOL reserve is read, not derived.
 *
 * SCOPE, and its limit stated plainly. This emits targets for T1–T7 only: 2,056
 * distinct mints and 5,598 (trigger, mint) positions. T0 fired on 38,802 mints, whose
 * inline list would be roughly 2.5 MB of SQL, so T0 is NOT re-priced and the report
 * says so. The consequence is that a re-priced trigger cannot be compared against a
 * re-priced baseline, which is a limitation rather than a detail.
 *
 * The targets come from `artifacts/phase-b-fired-targets.csv`, emitted by the same
 * script that produced the cells, so the population is defined once.
 *
 * Usage: pnpm curve:sql
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const NEWLINE = String.fromCharCode(10);
const csv = readFileSync('artifacts/phase-b-fired-targets.csv', 'utf8').trim().split(NEWLINE);
const header = (csv.shift() ?? '').split(',');
const idx = {
  trigger: header.indexOf('trigger'),
  mint: header.indexOf('mint'),
  entry: header.indexOf('entry_utc_ms'),
  exit: header.indexOf('exit_target_utc_ms'),
};

interface Target {
  readonly trigger: string;
  readonly mint: string;
  readonly entryUtcMs: number;
  readonly exitTargetUtcMs: number;
}
const all: Target[] = csv.map((line) => {
  const f = line.split(',');
  return {
    trigger: f[idx.trigger] as string,
    mint: f[idx.mint] as string,
    entryUtcMs: Number(f[idx.entry]),
    exitTargetUtcMs: Number(f[idx.exit]),
  };
});

const targets = all.filter((t) => t.trigger !== 'T0');
const mints = new Set(targets.map((t) => t.mint));

/*
   CHUNKED, because Dune refused a 496 KB query outright with "HTTP method not
   allowed" — a size limit reported as a method error. Three chunks of about 1,900
   positions each keep every query near 170 KB, and the chunk index travels in the
   filename so a partial run is visible rather than silently short.
*/
const CHUNKS = 3;
const chunkOf = (i: number): Target[] =>
  targets.filter((_, j) => j % CHUNKS === i);

const build = (part: Target[], index: number): string => `-- GENERATED by pnpm curve:sql from artifacts/phase-b-fired-targets.csv — do not edit here.
--
-- PHASE G ADDENDUM §A.4 — CURVE-STATE EXIT PRICES FOR THE PRE-MIGRATION CELLS.
--
-- CHUNK ${index + 1} of ${CHUNKS}: ${part.length} (trigger, mint) positions.
-- ${targets.length} positions over ${mints.size} distinct mints in total, T1–T7.
-- T0's 38,802 mints are NOT included; see the script header.
--
-- The price is the state the pump program itself reported at the last trade at or
-- before the target instant: virtualSolReserves / virtualTokenReserves. A curve's
-- reserves change only when someone trades, so this is exact between trades rather
-- than interpolated, and the lag from the target back to that trade is returned so
-- staleness is visible instead of assumed away.
--
-- Nothing is derived from the constant-product invariant. §A.3 found k is NOT constant
-- over a curve's life — the invariant-derived SOL reserve agreed with the reported one
-- for only 58.5% to 80.0% of events — so the SOL reserve is read, never computed.
WITH targets (trigger, mint, entry_utc_ms, exit_target_utc_ms) AS (
  VALUES
${part.map((t) => `    ('${t.trigger}', '${t.mint}', ${t.entryUtcMs}, ${t.exitTargetUtcMs})`).join(`,${NEWLINE}`)}
),

ev AS (
  SELECT
    t.mint,
    t.evt_block_time                                                                  AS block_time,
    t.evt_block_slot                                                                  AS slot,
    CAST(COALESCE(t.virtualSolReserves, t.virtual_sol_reserves) AS DOUBLE)             AS v_sol,
    CAST(COALESCE(t.virtualTokenReserves, t.virtual_token_reserves) AS DOUBLE)         AS v_token
  FROM pumpdotfun_solana.pump_evt_tradeevent t
  -- Phase B's own chronological split, read from artifacts/trigger-cells.json rather
  -- than assumed: the holdout half is 2026-08-17 to 2026-08-19, and the first version
  -- of this query used the WALLET-PERSISTENCE window by mistake and matched 0.1% of
  -- targets. One day of slack each side so a target at a boundary still has events.
  WHERE t.evt_block_date >= DATE '2026-08-16'
    AND t.evt_block_date <= DATE '2026-08-20'
    AND COALESCE(t.virtualTokenReserves, t.virtual_token_reserves) > 0
),

-- Only the events for mints we are pricing, joined once.
scoped AS (
  SELECT e.*
  FROM ev e
  WHERE e.mint IN (SELECT DISTINCT mint FROM targets)
),

/* The last event at or before each target instant, for both legs of the position.
   ROW_NUMBER over a join is the shape Trino handles best here: one pass over the
   scoped events per target, ordered by how close the event is to the target. */
entry_px AS (
  SELECT
    tg.trigger, tg.mint, tg.entry_utc_ms,
    s.v_sol, s.v_token, s.block_time, s.slot,
    ROW_NUMBER() OVER (PARTITION BY tg.trigger, tg.mint ORDER BY s.block_time DESC) AS rn
  FROM targets tg
  JOIN scoped s
    ON s.mint = tg.mint
   AND s.block_time <= from_unixtime(tg.entry_utc_ms / 1000e0)
),

exit_px AS (
  SELECT
    tg.trigger, tg.mint, tg.exit_target_utc_ms,
    s.v_sol, s.v_token, s.block_time, s.slot,
    ROW_NUMBER() OVER (PARTITION BY tg.trigger, tg.mint ORDER BY s.block_time DESC) AS rn
  FROM targets tg
  JOIN scoped s
    ON s.mint = tg.mint
   AND s.block_time <= from_unixtime(tg.exit_target_utc_ms / 1000e0)
),

trades_between AS (
  SELECT tg.trigger, tg.mint, COUNT(s.slot) AS n_trades_between
  FROM targets tg
  LEFT JOIN scoped s
    ON s.mint = tg.mint
   AND s.block_time > from_unixtime(tg.entry_utc_ms / 1000e0)
   AND s.block_time <= from_unixtime(tg.exit_target_utc_ms / 1000e0)
  GROUP BY 1, 2
)

SELECT
  tg.trigger,
  tg.mint,
  tg.entry_utc_ms,
  tg.exit_target_utc_ms,
  en.v_sol                                                     AS entry_v_sol,
  en.v_token                                                   AS entry_v_token,
  en.v_sol / NULLIF(en.v_token, 0)                             AS entry_price,
  to_unixtime(en.block_time) * 1000e0                          AS entry_event_utc_ms,
  ex.v_sol                                                     AS exit_v_sol,
  ex.v_token                                                   AS exit_v_token,
  ex.v_sol / NULLIF(ex.v_token, 0)                             AS exit_price,
  to_unixtime(ex.block_time) * 1000e0                          AS exit_event_utc_ms,
  -- How stale each read is. A price from a trade an hour before the target is still
  -- exact for a curve, but the reader should be able to see it.
  tg.entry_utc_ms - to_unixtime(en.block_time) * 1000e0        AS entry_lag_ms,
  tg.exit_target_utc_ms - to_unixtime(ex.block_time) * 1000e0  AS exit_lag_ms,
  tb.n_trades_between
FROM targets tg
LEFT JOIN entry_px en ON en.trigger = tg.trigger AND en.mint = tg.mint AND en.rn = 1
LEFT JOIN exit_px  ex ON ex.trigger = tg.trigger AND ex.mint = tg.mint AND ex.rn = 1
LEFT JOIN trades_between tb ON tb.trigger = tg.trigger AND tb.mint = tg.mint
ORDER BY 1, 2
`;

mkdirSync('ops/dune/generated', { recursive: true });
console.log(`${targets.length} (trigger, mint) positions over ${mints.size} distinct mints, T1-T7`);
console.log(
  `T0 excluded: ${all.length - targets.length} positions over ` +
    `${new Set(all.filter((t) => t.trigger === 'T0').map((t) => t.mint)).size} mints`,
);
for (let i = 0; i < CHUNKS; i += 1) {
  const part = chunkOf(i);
  const sql = build(part, i);
  const path = `ops/dune/generated/q15-curve-exit-prices-${i + 1}.sql`;
  writeFileSync(path, sql);
  console.log(`  ${path}  ${part.length} positions, ${(sql.length / 1024).toFixed(0)} KB`);
}
