/**
 * Phase H §1, second source — resolve the venue by EXECUTING PROGRAM, not by Dune's
 * curated venue list.
 *
 * WHY THIS EXISTS. The first source, `dex_solana.trades`, found no trade at all for 933
 * of the 2,056 conditional-trigger mints, and on that split the whole positive return
 * lived in the 933. That looked like an answer and it is not one: Jupiter's own snapshot
 * fields, stored locally, report a completed trade for 98.5% of those same mints, with a
 * median of 106 distinct traders in a five-minute window and a median $7,073 of
 * liquidity. `dex_solana.trades` only carries venues Dune has curated, so an absence
 * there is a fact about Dune's coverage — it is not a fact about the token. Reporting it
 * as tradelessness would have been the exact error this programme exists to refuse.
 *
 * `tokens_solana.transfers` is the venue-agnostic primitive: every SPL token movement,
 * whatever moved it, with `outer_executing_account` naming the program that executed the
 * top-level instruction. A venue nobody has decoded still appears here, by ID, which is
 * what the directive asks for — "an unrecognised program with meaningful volume is a
 * finding, not a residual".
 *
 * WHAT `outer_executing_account` IS, stated precisely because it is easy to overclaim.
 * It is the program of the OUTER instruction. For a swap sent straight to an AMM that is
 * the AMM's program. For a swap routed through an aggregator it is the AGGREGATOR, and
 * the pool program is one level down where this table does not reach. So this column
 * resolves "which program moved the token" exactly, and "which pool it traded against"
 * only when the trade was not routed. Routers are named as routers in the report and are
 * never counted as venues.
 *
 * Same shape as Q16 so the two can be compared row for row: absolute 5-minute buckets
 * from the bucket base, a per-mint summary row, and the two kinds told apart by an
 * explicit `grouping()` bitmask.
 *
 * Usage: pnpm program:sql
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const NEWLINE = String.fromCharCode(10);
/** One day before the holdout, so "was it moving before we saw it" has an answer. */
const READ_LO = '2026-08-16';
const READ_HI = '2026-08-20';
/** Bucket 0 starts here, matching Q16 exactly. */
const BUCKET_BASE = '2026-08-16 00:00:00';
const BUCKET_S = 300;
/** Chunks over the T0-only mints. Six keeps each query near 330 KB. */
const T0_CHUNKS = 6;

const lines = readFileSync('artifacts/phase-b-fired-targets.csv', 'utf8').trim().split(NEWLINE);
const header = (lines.shift() ?? '').split(',');
const iTrigger = header.indexOf('trigger');
const iMint = header.indexOf('mint');

const triggersOf = new Map<string, Set<string>>();
for (const line of lines) {
  const f = line.split(',');
  const mint = f[iMint] as string;
  const set = triggersOf.get(mint) ?? new Set<string>();
  set.add(f[iTrigger] as string);
  triggersOf.set(mint, set);
}
const fired = [...triggersOf.entries()];
const conditional = fired.filter(([, t]) => [...t].some((x) => x !== 'T0')).map(([m]) => m);
const t0Only = fired.filter(([, t]) => t.size === 1 && t.has('T0')).map(([m]) => m);

const fnv1a = (s: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
};
const ordered = [...t0Only].sort((a, b) => fnv1a(a) - fnv1a(b) || (a < b ? -1 : 1));

const build = (mints: readonly string[], label: string, note: string): string => `-- GENERATED by pnpm program:sql from artifacts/phase-b-fired-targets.csv — do not edit here.
--
-- PHASE H §1 — VENUE BY EXECUTING PROGRAM, FROM TOKEN TRANSFERS.
--
-- ${label}: ${mints.length} mints.
-- ${note}
--
-- dex_solana.trades carries only venues Dune has curated, and it had no row at all for
-- 933 of the 2,056 conditional-trigger mints while Jupiter's own stored fields report a
-- completed trade for 98.5% of them. An absence there is a fact about Dune's coverage,
-- not about the token. tokens_solana.transfers is the primitive that does not curate:
-- every SPL movement, with outer_executing_account naming the program that executed it.
--
-- outer_executing_account is the OUTER instruction's program. Sent straight to an AMM
-- that is the AMM. Routed through an aggregator it is the AGGREGATOR, and the pool
-- program is one level down where this table does not reach. Routers are named as
-- routers in the report and are never counted as venues.
--
-- Two row kinds in one result, told apart by the GROUPING bitmask in column "g":
--   g = 0   one row per (mint, program, action, 5-minute bucket)
--   g = 7   one summary row per mint
-- Buckets are ABSOLUTE 5-minute bins from ${BUCKET_BASE} UTC, identical to Q16,
-- so the 44,400 Phase B position windows are scored locally against both sources.
WITH targets (mint) AS (
  VALUES
${mints.map((m) => `    ('${m}')`).join(`,${NEWLINE}`)}
),

tf AS (
  SELECT
    t.token_mint_address                                            AS mint,
    t.outer_executing_account                                       AS program,
    t.action,
    t.block_time,
    t.tx_id,
    t.tx_signer,
    t.from_owner,
    t.to_owner,
    t.amount_usd
  FROM tokens_solana.transfers t
  WHERE t.block_date >= DATE '${READ_LO}'
    AND t.block_date <= DATE '${READ_HI}'
    AND t.token_mint_address IN (SELECT mint FROM targets)
),

binned AS (
  SELECT
    f.mint,
    f.program,
    f.action,
    f.tx_id,
    f.tx_signer,
    f.from_owner,
    f.to_owner,
    f.amount_usd,
    to_unixtime(f.block_time)                                       AS at_s,
    CASE
      WHEN f.block_time < TIMESTAMP '${BUCKET_BASE}' THEN -2
      ELSE CAST(FLOOR((to_unixtime(f.block_time) - to_unixtime(TIMESTAMP '${BUCKET_BASE}')) / ${BUCKET_S}e0) AS INTEGER)
    END                                                             AS bucket
  FROM tf f
)

SELECT
  grouping(program, action, bucket)                                 AS g,
  mint,
  program,
  action,
  bucket,
  COUNT(*)                                                          AS n_moves,
  COUNT(DISTINCT tx_id)                                             AS n_tx,
  COUNT(DISTINCT tx_signer)                                         AS n_signers,
  COUNT(DISTINCT from_owner)                                        AS n_from,
  COUNT(DISTINCT to_owner)                                          AS n_to,
  MIN(at_s)                                                         AS first_s,
  MAX(at_s)                                                         AS last_s,
  SUM(COALESCE(amount_usd, 0e0))                                    AS usd,
  COUNT_IF(amount_usd IS NULL)                                      AS n_usd_null,
  -- Meaningful on the summary rows: the holdout days, and the day before them.
  COUNT_IF(bucket >= 0)                                             AS n_moves_holdout,
  COUNT(DISTINCT tx_id) FILTER (WHERE bucket >= 0)                  AS n_tx_holdout,
  COUNT(DISTINCT tx_signer) FILTER (WHERE bucket >= 0)              AS n_signers_holdout,
  COUNT_IF(bucket = -2)                                             AS n_moves_before,
  COUNT(DISTINCT program)                                           AS n_programs
FROM binned
GROUP BY GROUPING SETS (
  (mint, program, action, bucket),
  (mint)
)
ORDER BY 2, 1, 5
`;

mkdirSync('ops/dune/generated', { recursive: true });
const emit = (path: string, sql: string): void => {
  writeFileSync(path, sql);
  console.log(`  ${path}  ${(sql.length / 1024).toFixed(0)} KB`);
};

console.log(`${fired.length} distinct mints: ${conditional.length} conditional, ${t0Only.length} T0-only`);
emit(
  'ops/dune/generated/q17-program-conditional.sql',
  build(
    conditional,
    'EVERY MINT THAT FIRED A CONDITIONAL TRIGGER T1-T7',
    'The population the +234.2% to +394.2% figures are computed over, in full and unsampled.',
  ),
);
const per = Math.ceil(ordered.length / T0_CHUNKS);
for (let i = 0; i < T0_CHUNKS; i += 1) {
  const part = ordered.slice(i * per, (i + 1) * per);
  emit(
    `ops/dune/generated/q17-program-baseline-${i + 1}.sql`,
    build(
      part,
      `T0-ONLY BASELINE MINTS, CHUNK ${i + 1} of ${T0_CHUNKS}`,
      'Ordered by FNV-1a of the mint so that a chunk is not one day of the corpus.',
    ),
  );
}
