/**
 * Phase F §2.3 — generate the reserve-reconstruction validation query.
 *
 * The directive asks for the reconstruction to be validated against the 142 pools
 * where real on-chain bytes are held, before any use at scale. This emits the SQL
 * with those anchors embedded, so that what ran is in version control rather than
 * assembled by hand.
 *
 * TWO TESTS, AND THE FIRST ONE ASSUMES NOTHING
 *
 *   PAIR TEST. 271 of the 413 snapshots are the second or later snapshot of a pool
 *   that has more than one. For each consecutive pair, roll the earlier stored
 *   reserves forward through the trades between the two SLOTS and compare with the
 *   later stored reserves. This needs no anchor and no assumption about the
 *   migration deposit: it asks only whether the trade stream fully explains how a
 *   pool's reserves changed. If it does not, nothing downstream can be trusted.
 *
 *   IMPLIED-INITIAL TEST. Roll each pool's earliest stored reserves BACK to its
 *   first observed trade. Under option B the answer should be the same constant for
 *   every pool, and the spread across pools measures whether B is a constant at all
 *   rather than assuming it.
 *
 * WHY THE PAIR TEST MIGHT FAIL, stated before it runs: `dex_solana.trades` records
 * the TRADER's amounts, and a PumpSwap swap splits its fee between the pool, the
 * protocol and the creator. The portion that leaves the pool is not in the trader's
 * amounts, so a naive roll-forward drifts by the fee split, cumulatively, trade by
 * trade. At 125 bps a leg that drift is not obviously below the 1% bar. That is the
 * technical risk §2.2 said to state rather than assume, and this query measures it.
 *
 * Slots, not timestamps: a snapshot carries the slot it was captured at, and
 * bounding the trade window by slot is exact where a wall-clock bound would include
 * or exclude whatever landed in the same second.
 *
 * Usage: pnpm anchors:sql   (writes ops/dune/generated/q9-reserve-validation.sql)
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

interface Anchor {
  readonly mint: string;
  readonly pool: string;
  readonly slot: number;
  readonly capturedUtcMs: number;
  readonly baseReserve: string | null;
  readonly quoteReserve: string | null;
  readonly readable: boolean;
}

const inv = JSON.parse(readFileSync('artifacts/phase-f-anchors.json', 'utf8')) as { anchors: Anchor[] };
const readable = inv.anchors.filter((a) => a.readable && a.baseReserve !== null && a.quoteReserve !== null);

// Order per pool, so a snapshot index makes "consecutive" well defined.
const byPool = new Map<string, Anchor[]>();
for (const a of readable) {
  const list = byPool.get(a.pool);
  if (list === undefined) byPool.set(a.pool, [a]);
  else list.push(a);
}
for (const list of byPool.values()) list.sort((x, y) => x.slot - y.slot);

const rows: string[] = [];
for (const [pool, list] of [...byPool.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  list.forEach((a, i) => {
    rows.push(
      `    ('${a.mint}', '${pool}', ${a.slot}, ${i}, DECIMAL '${a.baseReserve}', DECIMAL '${a.quoteReserve}')`,
    );
  });
}

const pairCount = [...byPool.values()].reduce((acc, l) => acc + Math.max(l.length - 1, 0), 0);
const minSlot = Math.min(...readable.map((a) => a.slot));
const maxSlot = Math.max(...readable.map((a) => a.slot));
const minDay = new Date(Math.min(...readable.map((a) => a.capturedUtcMs)) - 86_400_000)
  .toISOString()
  .slice(0, 10);
const maxDay = new Date(Math.max(...readable.map((a) => a.capturedUtcMs)) + 86_400_000)
  .toISOString()
  .slice(0, 10);

const sql = `-- GENERATED by pnpm anchors:sql from artifacts/phase-f-anchors.json — do not edit here.
--
-- PHASE F §2.3 — reserve reconstruction, validated against stored on-chain bytes.
--
-- ${readable.length} snapshots over ${byPool.size} pools, ${pairCount} consecutive pairs.
-- Slots ${minSlot} .. ${maxSlot}; partitions ${minDay} .. ${maxDay}.
--
-- The anchors below are the collector's OWN stored pool bytes, decoded through
-- poolFactsFrom. They are data, not a model: base and quote are raw units as the
-- chain holds them.
--
-- SIGN CONVENTION. A trade whose BOUGHT side is WSOL is a trader SELLING the token,
-- so the pool RECEIVES base and PAYS quote. A trade whose SOLD side is WSOL is a
-- trader buying, so the pool PAYS base and RECEIVES quote. Amounts are the raw
-- uint256 columns, matching the units of the stored reserves.
WITH anchors (mint, pool, slot, snap_index, base_stored, quote_stored) AS (
  VALUES
${rows.join(',\n')}
),

params AS (
  SELECT
    'So11111111111111111111111111111111111111112' AS wsol,
    DATE '${minDay}' AS day_lo,
    DATE '${maxDay}' AS day_hi
),

legs AS (
  SELECT
    t.block_slot,
    CASE WHEN t.token_bought_mint_address = p.wsol
         THEN t.token_sold_mint_address ELSE t.token_bought_mint_address END AS mint,
    -- The pool's own base delta, in raw units.
    CASE WHEN t.token_bought_mint_address = p.wsol
         THEN  CAST(t.token_sold_amount_raw   AS DECIMAL(38,0))
         ELSE -CAST(t.token_bought_amount_raw AS DECIMAL(38,0)) END AS base_delta,
    -- and its quote delta.
    CASE WHEN t.token_bought_mint_address = p.wsol
         THEN -CAST(t.token_bought_amount_raw AS DECIMAL(38,0))
         ELSE  CAST(t.token_sold_amount_raw   AS DECIMAL(38,0)) END AS quote_delta
  FROM dex_solana.trades t
  CROSS JOIN params p
  WHERE t.project = 'pumpswap'
    AND t.block_date >= p.day_lo
    AND t.block_date <= p.day_hi
    AND (t.token_bought_mint_address = p.wsol OR t.token_sold_mint_address = p.wsol)
),

-- TEST 1: consecutive pairs. No anchor assumption enters.
pairs AS (
  SELECT
    a.mint,
    a.pool,
    a.snap_index,
    a.slot                AS slot_from,
    b.slot                AS slot_to,
    a.base_stored         AS base_from,
    a.quote_stored        AS quote_from,
    b.base_stored         AS base_to,
    b.quote_stored        AS quote_to
  FROM anchors a
  JOIN anchors b ON b.pool = a.pool AND b.snap_index = a.snap_index + 1
),

pair_flows AS (
  SELECT
    pr.mint, pr.pool, pr.snap_index, pr.slot_from, pr.slot_to,
    pr.base_from, pr.quote_from, pr.base_to, pr.quote_to,
    COALESCE(SUM(l.base_delta), DECIMAL '0')  AS base_delta,
    COALESCE(SUM(l.quote_delta), DECIMAL '0') AS quote_delta,
    COUNT(l.block_slot)                       AS n_trades
  FROM pairs pr
  LEFT JOIN legs l
    ON l.mint = pr.mint
   AND l.block_slot > pr.slot_from
   AND l.block_slot <= pr.slot_to
  GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9
),

-- TEST 2: roll each pool's EARLIEST snapshot back to its first observed trade, so
-- the implied deposit can be compared across pools.
first_snap AS (
  SELECT mint, pool, slot, base_stored, quote_stored FROM anchors WHERE snap_index = 0
),

back_flows AS (
  SELECT
    f.mint, f.pool, f.slot, f.base_stored, f.quote_stored,
    COALESCE(SUM(l.base_delta), DECIMAL '0')  AS base_delta_since_first_trade,
    COALESCE(SUM(l.quote_delta), DECIMAL '0') AS quote_delta_since_first_trade,
    COUNT(l.block_slot)                       AS n_trades_before,
    MIN(l.block_slot)                         AS first_trade_slot
  FROM first_snap f
  LEFT JOIN legs l ON l.mint = f.mint AND l.block_slot <= f.slot
  GROUP BY 1, 2, 3, 4, 5
)

SELECT
  'PAIR'                                                       AS test,
  pf.mint,
  pf.pool,
  pf.snap_index,
  pf.slot_from,
  pf.slot_to,
  pf.n_trades,
  CAST(pf.base_from  AS VARCHAR)                               AS base_from,
  CAST(pf.quote_from AS VARCHAR)                               AS quote_from,
  CAST(pf.base_to    AS VARCHAR)                               AS base_stored,
  CAST(pf.quote_to   AS VARCHAR)                               AS quote_stored,
  CAST(pf.base_from  + pf.base_delta  AS VARCHAR)              AS base_reconstructed,
  CAST(pf.quote_from + pf.quote_delta AS VARCHAR)              AS quote_reconstructed,
  CAST(pf.base_delta  AS VARCHAR)                              AS base_delta,
  CAST(pf.quote_delta AS VARCHAR)                              AS quote_delta,
  CAST((pf.base_from  + pf.base_delta)  AS DOUBLE) / NULLIF(CAST(pf.base_to  AS DOUBLE), 0) AS base_ratio,
  CAST((pf.quote_from + pf.quote_delta) AS DOUBLE) / NULLIF(CAST(pf.quote_to AS DOUBLE), 0) AS quote_ratio
FROM pair_flows pf

UNION ALL

SELECT
  'IMPLIED_INITIAL'                                            AS test,
  bf.mint,
  bf.pool,
  0                                                            AS snap_index,
  COALESCE(bf.first_trade_slot, 0)                             AS slot_from,
  bf.slot                                                      AS slot_to,
  bf.n_trades_before                                           AS n_trades,
  CAST(bf.base_stored  AS VARCHAR)                             AS base_from,
  CAST(bf.quote_stored AS VARCHAR)                             AS quote_from,
  CAST(bf.base_stored  AS VARCHAR)                             AS base_stored,
  CAST(bf.quote_stored AS VARCHAR)                             AS quote_stored,
  -- The implied state before the first observed trade: stored minus everything since.
  CAST(bf.base_stored  - bf.base_delta_since_first_trade  AS VARCHAR) AS base_reconstructed,
  CAST(bf.quote_stored - bf.quote_delta_since_first_trade AS VARCHAR) AS quote_reconstructed,
  CAST(bf.base_delta_since_first_trade  AS VARCHAR)            AS base_delta,
  CAST(bf.quote_delta_since_first_trade AS VARCHAR)            AS quote_delta,
  CAST(NULL AS DOUBLE)                                         AS base_ratio,
  CAST(NULL AS DOUBLE)                                         AS quote_ratio
FROM back_flows bf

ORDER BY 1, 3, 4
`;

mkdirSync('ops/dune/generated', { recursive: true });
writeFileSync('ops/dune/generated/q9-reserve-validation.sql', sql);
console.log(`wrote ops/dune/generated/q9-reserve-validation.sql`);
console.log(`  ${readable.length} anchors over ${byPool.size} pools`);
console.log(`  ${pairCount} consecutive pairs for the assumption-free pair test`);
console.log(`  ${byPool.size} pools for the implied-initial test`);
console.log(`  slots ${minSlot} .. ${maxSlot}, partitions ${minDay} .. ${maxDay}`);
console.log(`  ${sql.split('\n').length} lines`);
