/**
 * Phase H §1 — generate the venue-classification query.
 *
 * The question is where the +234.2% to +394.2% trigger means live. PR #64 established
 * that only 999 of 5,598 T1–T7 holdout positions are pump.fun bonding-curve mints and
 * that the curve subset's T1 mean is −32.47%, so the positive figures belong to a
 * population that has never been named.
 *
 * WHICH COLUMN IS THE PROGRAM. The first run of this query took
 * `dex_solana.trades.project_program_id` for the program ID and it is not one: its
 * values are per-mint, 1,319 distinct over 2,056 mints, which is a pool. Both
 * `project_program_id` and `project_main_id` are therefore selected here and the report
 * names which one is the program, alongside Dune's own `project` and `version_name`.
 * A program the table does not name is reported by its raw ID and never bucketed.
 *
 * WHAT COMES BACK. One row per (mint, program, 5-minute bucket) and one summary row per
 * mint, in a single result told apart by an explicit `grouping()` bitmask — NOT by a
 * null program, which was the first run's other defect: 6,139 pumpdotfun rows carry a
 * null `project_program_id` of their own, so the null test silently mixed 7,046 rows of
 * two different kinds.
 *
 * BUCKETS ARE ABSOLUTE, not relative to the mint's first trade. Absolute buckets let
 * the 44,400 Phase B position windows be scored locally without those windows having to
 * travel INTO the SQL — 44,400 inline windows would be about 2.7 MB and Dune refuses a
 * query near 500 KB with a method error. They also survive the wider read below, which
 * a first-trade-relative bucket does not: a mint that traded ten days before the
 * holdout would put its whole position window in the overflow bucket.
 *
 * THE READ IS WIDER THAN THE HOLDOUT ON PURPOSE. 45% of the conditional-trigger mints
 * had no `dex_solana.trades` row at all over the holdout days. That is either a token
 * that never traded, or a token that is not new and traded earlier — a distinction
 * worth two credits, because Jupiter's `tokenAgeMs` claims every one of them is minutes
 * old. Trades before the holdout window collapse into bucket −2 rather than being
 * dropped, so one scan answers both.
 *
 * DISTINCT TRADERS ARE NOT SUMMABLE, so they are not summed. The summary row carries an
 * exact distinct-trader count over the holdout days, which is a GENEROUS UPPER BOUND on
 * the traders present in any single holding window; the per-bucket counts give the other
 * side of the sandwich. A thin-data test that still fires against an upper bound has
 * fired robustly.
 *
 * ONE SCAN, NOT TWO. The mint set is applied as a semi-join in the WHERE clause rather
 * than as two joins unioned together: Trino inlines CTEs, so the union form would read
 * the whole window twice and cost twice as much.
 *
 * Usage: pnpm venue:sql
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const NEWLINE = String.fromCharCode(10);
/** Ten days before the holdout, to tell "never traded" from "not new". */
const READ_LO = '2026-08-06';
const READ_HI = '2026-08-20';
/** Bucket 0 starts here. Every Phase B entry and exit is at or after this instant. */
const BUCKET_BASE = '2026-08-16 00:00:00';
/** 5 minutes. Short enough that a position's 15-58 minute window is well resolved. */
const BUCKET_S = 300;
/** Chunks over the T0-only mints. Six keeps each query near 330 KB. */
const T0_CHUNKS = 6;

const lines = readFileSync('artifacts/phase-b-fired-targets.csv', 'utf8').trim().split(NEWLINE);
const header = (lines.shift() ?? '').split(',');
const iTrigger = header.indexOf('trigger');
const iMint = header.indexOf('mint');

const triggersOf = new Map<string, Set<string>>();
for (const line of lines) {
  const f = line.split(',');
  const mint = f[iMint] as string;
  const set = triggersOf.get(mint) ?? new Set<string>();
  set.add(f[iTrigger] as string);
  triggersOf.set(mint, set);
}

const fired = [...triggersOf.entries()];
const conditional = fired.filter(([, t]) => [...t].some((x) => x !== 'T0')).map(([m]) => m);
const t0Only = fired.filter(([, t]) => t.size === 1 && t.has('T0')).map(([m]) => m);

/*
   FNV-1a over the mint string, used ONLY to order the T0-only mints so that a chunk
   boundary does not follow the corpus's own ordering, which is by day and would put one
   day of the corpus in one chunk. No randomness, so there is no seed to lose.
*/
const fnv1a = (s: string): number => {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
};
const ordered = [...t0Only].sort((a, b) => fnv1a(a) - fnv1a(b) || (a < b ? -1 : 1));

const build = (mints: readonly string[], label: string, note: string): string => `-- GENERATED by pnpm venue:sql from artifacts/phase-b-fired-targets.csv — do not edit here.
--
-- PHASE H §1 — VENUE OF THE ENTRY LEG, BY PROGRAM ID.
--
-- ${label}: ${mints.length} mints.
-- ${note}
--
-- Two row kinds in one result, told apart by the GROUPING bitmask in column "g":
--   g = 0   one row per (mint, project, program, version, 5-minute bucket)
--   g = 15  one summary row per mint
-- The null-program test used on the first run does NOT tell them apart: pumpdotfun
-- rows carry a null project_program_id of their own.
--
-- Buckets are ABSOLUTE 5-minute bins from ${BUCKET_BASE} UTC, so the 44,400
-- Phase B position windows can be scored locally. Putting those windows in the SQL
-- would be about 2.7 MB and Dune refuses a query near 500 KB with a method error.
-- Trades before the bucket base collapse into bucket -2 instead of being dropped: the
-- read starts ${READ_LO}, ten days early, to tell a token that never traded from a
-- token that is not new. Jupiter's tokenAgeMs claims all of them are minutes old.
--
-- Distinct traders are not summable and are not summed. The summary row carries an
-- exact distinct-trader count over the holdout days, a GENEROUS UPPER BOUND on the
-- traders in any one holding window; the per-bucket counts give the lower side.
WITH targets (mint) AS (
  VALUES
${mints.map((m) => `    ('${m}')`).join(`,${NEWLINE}`)}
),

/* ONE SCAN. The mint set is a semi-join in the WHERE clause rather than two joins
   unioned together: Trino inlines CTEs, so the union form would read the whole window
   twice. A trade with BOTH sides in the set is attributed to the bought side; that is
   one of our tokens traded directly against another, which is rare, and the alternative
   double-counts it. */
tr AS (
  SELECT
    CASE
      WHEN t.token_bought_mint_address IN (SELECT mint FROM targets) THEN t.token_bought_mint_address
      ELSE t.token_sold_mint_address
    END                                                            AS mint,
    t.project,
    t.project_main_id,
    t.project_program_id,
    t.version_name,
    t.trade_source,
    t.block_time,
    t.trader_id,
    t.amount_usd,
    t.fee_usd,
    CASE WHEN t.token_bought_mint_address IN (SELECT mint FROM targets) THEN 1 ELSE 0 END AS is_buy
  FROM dex_solana.trades t
  WHERE t.block_date >= DATE '${READ_LO}'
    AND t.block_date <= DATE '${READ_HI}'
    AND (
      t.token_bought_mint_address IN (SELECT mint FROM targets)
      OR t.token_sold_mint_address IN (SELECT mint FROM targets)
    )
),

binned AS (
  SELECT
    r.mint,
    r.project,
    r.project_main_id,
    r.project_program_id,
    r.version_name,
    r.trade_source,
    r.trader_id,
    r.amount_usd,
    r.fee_usd,
    r.is_buy,
    to_unixtime(r.block_time)                                      AS at_s,
    CASE
      WHEN r.block_time < TIMESTAMP '${BUCKET_BASE}' THEN -2
      ELSE CAST(FLOOR((to_unixtime(r.block_time) - to_unixtime(TIMESTAMP '${BUCKET_BASE}')) / ${BUCKET_S}e0) AS INTEGER)
    END                                                            AS bucket
  FROM tr r
)

SELECT
  grouping(project, project_main_id, version_name, bucket)         AS g,
  mint,
  project,
  project_main_id,
  version_name,
  bucket,
  COUNT(*)                                                        AS n_trades,
  COUNT(DISTINCT trader_id)                                        AS n_traders,
  SUM(is_buy)                                                      AS n_buys,
  MIN(at_s)                                                        AS first_s,
  MAX(at_s)                                                        AS last_s,
  SUM(COALESCE(amount_usd, 0e0))                                   AS usd,
  COUNT_IF(amount_usd IS NULL)                                     AS n_usd_null,
  SUM(COALESCE(fee_usd, 0e0))                                      AS fee_usd,
  COUNT_IF(fee_usd IS NULL)                                        AS n_fee_null,
  COUNT(DISTINCT project_program_id)                               AS n_pools,
  COUNT(DISTINCT project_main_id)                                  AS n_programs,
  COUNT(DISTINCT trade_source)                                     AS n_sources,
  -- Only meaningful on the summary rows: the holdout days on their own.
  COUNT_IF(bucket >= 0)                                            AS n_trades_holdout,
  COUNT(DISTINCT trader_id) FILTER (WHERE bucket >= 0)             AS n_traders_holdout,
  COUNT_IF(bucket = -2)                                            AS n_trades_before
FROM binned
GROUP BY GROUPING SETS (
  (mint, project, project_main_id, version_name, bucket),
  (mint)
)
ORDER BY 2, 1, 6
`;

mkdirSync('ops/dune/generated', { recursive: true });
const emit = (path: string, sql: string): void => {
  writeFileSync(path, sql);
  console.log(`  ${path}  ${(sql.length / 1024).toFixed(0)} KB`);
};

console.log(
  `${fired.length} distinct mints fired: ${conditional.length} fired a conditional trigger, ` +
    `${t0Only.length} fired T0 only`,
);
emit(
  'ops/dune/generated/q16-venue-conditional.sql',
  build(
    conditional,
    'EVERY MINT THAT FIRED A CONDITIONAL TRIGGER T1-T7',
    'This is the population the +234.2% to +394.2% figures are computed over, in full and unsampled.',
  ),
);
const per = Math.ceil(ordered.length / T0_CHUNKS);
for (let i = 0; i < T0_CHUNKS; i += 1) {
  const part = ordered.slice(i * per, (i + 1) * per);
  emit(
    `ops/dune/generated/q16-venue-baseline-${i + 1}.sql`,
    build(
      part,
      `T0-ONLY BASELINE MINTS, CHUNK ${i + 1} of ${T0_CHUNKS}`,
      'Ordered by FNV-1a of the mint so that a chunk is not one day of the corpus. The baseline is ' +
        'exact rather than sampled because the conditional chunk measured at 0.78 credits.',
    ),
  );
}
